package debugger.encoding

import kotlinx.serialization.Serializable

/**
 * Represents a single debug instruction executed at each iteration or at specific lines.
 *
 * Used for encoding debug information to be outputted as JSON.
 *
 * @property pc The program counter-value (as a string) at which this instruction is executed.
 * @property instructionType The type of debug instruction (e.g. "registers", "memoryRange").
 * @property dataOutput The data output generated by the debug instruction, represented as a map of strings to nullable longs.
 */
@Serializable
data class EachInstruction(val pc: String, val instructionType: String, val dataOutput: Map<String, Long?>)